[package]
name = "new_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
nalgebra = "0.29.0"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["gfx"]