[package]
name = "rusty_graphics"
version = "0.0.1"
edition = "2021"

[dependencies]
nalgebra = "0.29.0"
rusty_physics = { path = "../rusty_physics"}

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["gfx"]